/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BcdRating {
        /**
          * The max rating
         */
        "max": number;
        /**
          * The rating
         */
        "rating": number;
    }
}
declare global {
    interface HTMLBcdRatingElement extends Components.BcdRating, HTMLStencilElement {
    }
    var HTMLBcdRatingElement: {
        prototype: HTMLBcdRatingElement;
        new (): HTMLBcdRatingElement;
    };
    interface HTMLElementTagNameMap {
        "bcd-rating": HTMLBcdRatingElement;
    }
}
declare namespace LocalJSX {
    interface BcdRating {
        /**
          * The max rating
         */
        "max"?: number;
        /**
          * The rating
         */
        "rating"?: number;
    }
    interface IntrinsicElements {
        "bcd-rating": BcdRating;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "bcd-rating": LocalJSX.BcdRating & JSXBase.HTMLAttributes<HTMLBcdRatingElement>;
        }
    }
}
